# Generated by Django 4.2.14 on 2024-07-24 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_breaking_news',
            field=models.BooleanField(default=False),
        ),
    ]
